### ISSUE TITLE
PartialReadError on 1.18

### ISSUE THREAD

**Issue by imharvol** [imharvol/mineflayer-web-inventory#32]
As can be seen in this CI run https://github.com/imharvol/mineflayer-web-inventory/runs/6212744006?check_suite_focus=true#step:6:91, a `PartialReadError: Read error for undefined : undefined` is thrown. 

```
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/utils.js:70:5)
    at Object.readVarInt [as varint] (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/datatypes/utils.js:69:45)
    at eval (eval at compile (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:258:12), <anonymous>:631:67)
    at eval (eval at compile (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:258:12), <anonymous>:641:13)
    at eval (eval at compile (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:258:12), <anonymous>:768:11)
    at Object.packet_declare_commands (eval at compile (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:258:12), <anonymous>:773:9)
    at eval (eval at compile (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2162:72)
    at packet (eval at compile (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2253:9)
    at CompiledProtodef.read (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/compiler.js:111:29)
    at FullPacketParser.parsePacketBuffer (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/serializer.js:68:23)
    at FullPacketParser._transform (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/protodef/src/serializer.js:74:21)
    at FullPacketParser.Transform._read (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at FullPacketParser.Writable.write (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Decompressor.ondata (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Decompressor.emit (events.js:400:28)
    at addChunk (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Decompressor.Readable.push (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Decompressor.Transform.push (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Unzip.cb (/home/runner/work/mineflayer-web-inventory/mineflayer-web-inventory/node_modules/minecraft-protocol/src/transforms/compression.js:69:14)
    at Unzip.zlibBufferOnEnd (zlib.js:158:10)
    at Unzip.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Only happens with Minecraft 1.18.2 and doesn't appear to stop mineflayer nor mineflayer-web-inventory from working

**Comment by imharvol** [comment]
Error has nothing to do with mineflayer-web-inventory, it's also shown in mineflayer's own tests.
